---
title: "About"
pagetitle: "About · Theodor Balan"
---

<main>

::: {.wrap}

I'm a data scientist with a background in biostatistics and mathematics. I'm interested in causal inference, experimentation, survival analysis and machine learning. I mostly code in R, and am the author and maintainer of the [frailtyEM](https://CRAN.R-project.org/package=frailtyEM) package. I have a PhD from Leiden University based on methodological research in [frailty models](https://hdl.handle.net/1887/66031).

I currently work as a senior data scientist at [Booking.com](https://www.booking.com), focused on causal inference and experimentation for two-sided marketplaces. Before that I spent three years at Danone Nutricia Research building statistical and machine-learning solutions for early life nutrition and medical foods, and five years in academia at the Leiden University Medical Center.

For more info you can send me an [email](mailto:hello@tbalan.com), check out some of my code on [Github](https://github.com/tbalan/), my work & education history on [LinkedIn](https://www.linkedin.com/in/thbalan/), my peer-reviewed publications on [Google Scholar](https://scholar.google.com/citations?user=-v5tVyUAAAAJ&hl=en) or my occasional blog posts on [Medium](https://medium.com/@thbalan).

:::

</main>
